Docs/Tag
gpn-prototypes/ui-kit pull request #323
Opened 2020-08-09 14:54 UTC by arhayka

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](../docs/commits-style.md)

2020-08-20 08:52 UTC, arhayka commented
@fooontic посмотри, пожалуйста. я не очень поняла, как работают типы тегов — надо поправить

2020-08-30 21:05 UTC, fooontic requested changes

2020-08-30 21:05 UTC, fooontic commented on src/components/Tag/__stories__/Tag.mdx
> +<TagExampleText />
Тут мне кажется пример коды излишен.

2020-08-30 21:05 UTC, fooontic commented on src/components/Tag/__stories__/examples/TagExampleIcon/TagExampleIcon.tsx
> +    <Tag mode="buttin" icon={IconSun} label="Солнце" />
опечатка butt**o**n

2020-08-30 21:05 UTC, fooontic commented on src/components/Tag/__stories__/Tag.mdx
> +<Tag mode="buttin" icon={IconSun} label="Солнце" />
опечатка из примера приехала butt**o**n

2020-08-31 06:16 UTC, gizeasy requested changes

2020-08-31 06:16 UTC, gizeasy commented on src/components/Tag/__stories__/Tag.mdx
> +## Типы тегов
Может Режим? или Режим работы?

2020-08-31 06:16 UTC, gizeasy commented on src/components/Tag/__stories__/Tag.mdx
> +иконку `IconClose`.
чтобы иконка отобразилась нужно передать функцию в onCancel.

2020-08-31 06:16 UTC, gizeasy commented on src/components/Tag/__stories__/Tag.mdx
> +
в таблице нет указания обязательных / необязательных полей

раньше были

| Свойство   | Тип                                                                           | По умолчанию | Описание                                                                 |	
| ---------- | ----------------------------------------------------------------------------- | ------------ | ------------------------------------------------------------------------ |	
| label      | `string`                                                                      | -            | Текст на тэге                                                            |	
| mode       | `'check' , 'button' , 'cancel' ,'link'`                                       | `'button'`   | Режим                                                                    |	
| onClick?   | `React.MouseEventHandler, never`                                              | -            | Событие клика по тэгу. Доступно только при `mode` = `'button'`, `'link'` |	
| onCancel?  | `React.MouseEventHandler, never`                                              | -            | Событие клика по крестику. Доступно только при `mode` = `'cancel'`       |	
| onChange?  | `({ e, checked }: { e?: React.MouseEvent; checked: boolean }) => void, never` | -            | Событие клика по тэгу. Доступно только при `mode` = `'check'`            |	
| checked?   | `boolean, never`                                                              | -            | Пометка выбранного элемента. Доступно только при `mode` = `'check'`      |	
| size?      | `'xs' , 's' , 'm' , 'l'`                                                      | `'m'`        | Размер                                                                   |	
| group?     | `1..9, '1'...'9'`                                                             | -            | Метка группы                                                             |	
| icon?      | `React.FC<IconProps>`                                                         | -            | Иконка                                                                   |	
| className? | `string`                                                                      | -            | Дополнительный класс                                                     |	
| ref?       | `React.Ref<HTMLElement>`                                                      | -            | Ссылка на корневой DOM элемент компонента                                |

2020-08-31 11:22 UTC, gizeasy commented on src/components/Tag/__stories__/Tag.mdx
> +<TagExampleText />
я за единообразие, мне кажется лучше пусть будет

2020-08-31 11:27 UTC, gizeasy commented on src/components/Tag/__stories__/Tag.mdx
> +<TagExampleMode />
fix

2020-08-31 11:27 UTC, gizeasy commented on src/components/Tag/__stories__/Tag.mdx
> +иконку `IconClose`.
fix

2020-08-31 11:27 UTC, gizeasy commented on src/components/Tag/__stories__/Tag.mdx
> +
fix

2020-08-31 14:40 UTC, gizeasy approved these changes

2020-08-31 21:57 UTC, fooontic commented on src/components/Tag/__stories__/Tag.mdx
> +<TagExampleText />
Ну мы же не везде пишем примеры кода, всё равно. Там где описание касается не метода, а просто общее описание мне кажется там нет нужды в коде.

2020-08-31 21:57 UTC, fooontic approved these changes

2020-09-01 05:18 UTC, merged