Docs/TextField
gpn-prototypes/ui-kit pull request #324
Opened 2020-08-09 20:35 UTC by arhayka

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](../docs/commits-style.md)

2020-08-24 13:21 UTC, fooontic approved these changes

2020-08-24 13:21 UTC, fooontic commented on src/components/TextField/__stories__/TextField.mdx
> +Свойство `type` определяет тип поля и тег, которым оно будет задаваться.
Вроде тип может быть любой, который может быть у инпута. Но надо проверить точнее. тут @gizeasy  подскажет разве что. Если я прав, но надо написать так, что у нас описано два состояния, но если вам надо number например — велком.

2020-08-24 13:21 UTC, fooontic commented on src/components/TextField/__stories__/TextField.mdx
> +<TextFieldExampleStatus />
Надо понять почему в примерах не работает набор текста. @gizeasy

2020-08-24 13:21 UTC, fooontic commented on src/components/TextField/__stories__/TextField.mdx
> +<TextField type="textarea" rows="13"  cols="25" value="Я иду и пою обо всем хорошем и улыбку свою я дарю прхожим"/>
*прОхожим

2020-08-24 13:24 UTC, fooontic requested changes
Случайно аппрувнул, но нужны будут доработки небольшие по комментам выше.

2020-08-31 06:18 UTC, gizeasy commented on src/components/TextField/__stories__/TextField.mdx
> +Свойство `type` определяет тип поля и тег, которым оно будет задаваться.
да ты прав `type?: string;`

2020-08-31 06:25 UTC, gizeasy requested changes

2020-08-31 06:25 UTC, gizeasy commented on src/components/TextField/__stories__/TextField.mdx
> +| `inputRef`  | `React.Ref<HTMLTextAreaElement | HTMLInputElement>>`  | -  | Ссылка на корневой DOM-элемент компонента                                |
![image](https://user-images.githubusercontent.com/13190808/91688773-75e21400-eb6b-11ea-9205-f757ad57dd08.png)

напиши через запятую

| `inputRef`  | `React.Ref<HTMLTextAreaElement, HTMLInputElement>>`  | -  | Ссылка на корневой DOM-элемент компонента |

2020-08-31 06:25 UTC, gizeasy commented on src/components/TextField/__stories__/TextField.mdx
> +| `onChange`  | `` | - | Действие при изменении текстового поля |
указать onChange. сам укажу, написал чтоб не забыть

2020-08-31 06:34 UTC, gizeasy requested changes

2020-08-31 06:34 UTC, gizeasy commented on src/components/TextField/__stories__/examples/TextFieldExampleForm/TextFieldExampleForm.tsx
> +export function TextFieldExampleFormBasic() {
может завернуть в `StoryBookExample`
чтобы отступы нормальные были? А то пример к коду прилип

2020-08-31 06:34 UTC, gizeasy commented on src/components/TextField/__stories__/examples/TextFieldExampleForm/TextFieldExampleForm.tsx
> +      <div className={cnDocsExample()}>
не нужный класс, когда с мержится с мастером, скорее всего сьедут стили. 
обнови локальный дев у себя

2020-08-31 09:04 UTC, arhayka commented on src/components/TextField/__stories__/TextField.mdx
> +Свойство `type` определяет тип поля и тег, которым оно будет задаваться.
а я бы оставила варианты text и textarea в документации. потому что иначе будет какая-нибудь фигня

2020-08-31 11:33 UTC, gizeasy commented on src/components/TextField/__stories__/TextField.mdx
> +Свойство `type` определяет тип поля и тег, которым оно будет задаваться.
мы этот вопрос уже поднимали и решили, что оставим эту ответственность пользователю.

2020-08-31 14:38 UTC, gizeasy commented on src/components/TextField/__stories__/TextField.mdx
> +<TextFieldExampleStatus />
fix

2020-08-31 14:38 UTC, gizeasy commented on src/components/TextField/__stories__/TextField.mdx
> +<TextField type="textarea" rows="13"  cols="25" value="Я иду и пою обо всем хорошем и улыбку свою я дарю прхожим"/>
fix

2020-08-31 14:39 UTC, gizeasy commented on src/components/TextField/__stories__/TextField.mdx
> +| `inputRef`  | `React.Ref<HTMLTextAreaElement | HTMLInputElement>>`  | -  | Ссылка на корневой DOM-элемент компонента                                |
fix

2020-08-31 14:39 UTC, gizeasy commented on src/components/TextField/__stories__/TextField.mdx
> +| `onChange`  | `` | - | Действие при изменении текстового поля |
fix

2020-08-31 14:41 UTC, gizeasy approved these changes

2020-08-31 21:45 UTC, fooontic approved these changes

2020-09-01 05:19 UTC, merged