Docs/User
gpn-prototypes/ui-kit pull request #326
Opened 2020-08-10 12:32 UTC by arhayka

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](../docs/commits-style.md)

2020-08-24 13:30 UTC, fooontic requested changes

2020-08-24 13:30 UTC, fooontic commented on src/components/User/__stories__/User.mdx
> +можно посмотреть подробную информацию о человеке.
Тут ещё бы добавить, что может раскрывать дополнительное контекстсное меню. Например, в шапке, где может быть: «Мой профиль», «Настройки профиля», ... , «Выйти».

2020-08-31 06:38 UTC, gizeasy requested changes

2020-08-31 06:38 UTC, gizeasy commented on src/components/User/__stories__/User.mdx
> +  <User avatarUrl="https://i.ibb.co/K2R8Lqb/Rectangle-1496.png" name="Люций" info="Эксперт"  onlyAvatar/>
удали пробелы в начали строк
![image](https://user-images.githubusercontent.com/13190808/91689846-94490f00-eb6d-11ea-8f20-e9261fc845e5.png)

2020-08-31 14:42 UTC, gizeasy approved these changes

2020-08-31 21:52 UTC, fooontic approved these changes

2020-09-01 05:39 UTC, merged