docs(Popover): edit text and structure
gpn-prototypes/ui-kit pull request #356
Opened 2020-08-24 09:28 UTC by arhayka

## Описание изменений

## Чек-лист

- [ ] PR: направлен в правильную ветку
- [ ] PR: назначен исполнитель PR и указаны нужные лейблы
- [ ] PR: проверен diff, ничего лишнего в PR не попало
- [ ] PR: прилинкованы затронутые issue и связанные PR
- [ ] PR: есть описание изменений
- [ ] JS: нет варнингов и ошибок в консоли браузера
- [ ] Тесты: новый функционал и исправленные баги покрыты тестами
- [ ] Документация: отражены все изменения в API компонентов и описаны важные особенности реализации или использования
- [ ] Сторибук: для компонентов написаны или обновлены stories
- [ ] Верстка: используются [переменные](../src/components/Theme)
- [ ] Верстка: проверена с разным количеством контента

## Опционально

- [ ] Доработки: заведены задачи для дальнейшей работы, если что-то решено не править в текущем пулл-реквесте
- [ ] Коммиты: проименованы в соответствии с [правилами](https://ui-kit.gpn.vercel.app/?path=/docs/common-develop-commits-style--page)

2020-08-25 08:21 UTC, nekitk approved these changes

2020-08-25 08:21 UTC, nekitk commented on src/components/Popover/__stories__/Popover.mdx
> +с помощью метода `getBoundingClientRect`.
с помощью метода `getBoundingClientRect` можно положить не размер вьюпорта, а положение элемента относительно вьюпорта. чтобы взять позицию элемента, а потом вычислить какую-нибудь точку этого элемента и передать в position. например, центр элемента.

наверное, это предложение можно и убрать.

2020-08-25 08:21 UTC, nekitk commented on src/components/Popover/__stories__/Popover.mdx
> +Содержимое поповера можно указать внутри или передать в свойстве `children`.
> указать внутри или передать в свойстве `children`.

по сути это одно и то же, т.к. то что мы кладём внутрь компонента передаётся в свойство `children`

тут наверное можно пояснить, что в children можно передать как обычные Реакт-элементы (`React.ReactNode`), так и рендерпроп, которая на вход получает направление разворота (`(direction: Direction) => React.ReactNode`).

использовать рендерпроп может быть полезно в тех случаях, когда внешний вид содержимого зависит от направления разворота. например, у тултипа в зависимости от направления разворота позиционируется ушко.

2020-08-27 20:41 UTC, fooontic requested changes

2020-08-27 20:41 UTC, fooontic commented on src/components/Popover/__stories__/Popover.mdx
> -Поповер - компонент для позиционирования на экране элементов, привязанных к координате или якорю. Например, для тултипов и дропдаунов.
Тут важно добавить, что это скорее логический компонент и не имеет стилей. Потому он не является до конца самостоятельным компонентом. А используется он при этом много где (в тултипе, в фильтрации в таблицах, в селектах и т.д.). Может быть полезен для создания различных контекстных меню и тому подобное.

2020-08-31 06:48 UTC, gizeasy commented
@fooontic @Miocene @arhayka Документация имеет 2е песочницы, в остальных компонентах только одну, оставим так или подумаем как сделать все единообразно?

2020-08-31 06:48 UTC, gizeasy requested changes

2020-08-31 06:48 UTC, gizeasy commented on src/components/Popover/__stories__/Popover.mdx
> +
нет указания обязательности полей
`direction?`

2020-09-01 05:50 UTC, gizeasy approved these changes

2020-09-01 05:50 UTC, gizeasy approved these changes

2020-09-01 07:16 UTC, merged